name: climpred-workshop
channels:
  - conda-forge
dependencies:
  - xesmf
  - esmpy
  - jupyter
  - netcdf4
  - numpy
  - xarray
  - bottleneck
  - xskillscore
  - cartopy
  - matplotlib
  - nc-time-axis
  - traitlets
  - zarr
  - gcsfs
  - statsmodels
  - pip
  - pip:
      - proplot
      # Install from master to get recent updates.
      - git+https://github.com/bradyrx/climpred@master
      - git+https://github.com/NCAR/pop-tools
      - rise

